"""empty message

Revision ID: c10a679f06aa
Revises: 3a55fa877c15
Create Date: 2023-08-11 09:14:39.159261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10a679f06aa'
down_revision = '3a55fa877c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pictures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pictures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
