"""Recreate migrations

Revision ID: d490a608f070
Revises: 9857c5d068cd
Create Date: 2023-09-01 11:59:58.245183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd490a608f070'
down_revision = '9857c5d068cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pictures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pictures_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pictures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pictures_username'))

    op.drop_table('pictures')
    # ### end Alembic commands ###
